--- 
title: "Aprendizaje de máquina"
author: "Felipe González"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
bibliography: [referencias/book.bib]
documentclass: book
biblio-style: apalike
link-citations: yes
github-repo: felipegonzalez/aprendizaje-maquina-mcd
description: "Notas y material para el curso de aprendizaje de máquina (ITAM, 2021)"
---


# Temario y referencias {-}

**Todas las notas y material del curso estarán en este** [repositorio](https://github.com/felipegonzalez/aprendizaje-maquina-mcd-2021).

- Introducción al aprendizaje máquina
- Métodos locales y regresión lineal
- Ingeniería de variables de entrada 
- Regularización
- Problemas de clasificación y regresión logística
- Métodos de remuestreo y validación cruzada
- Redes neuronales
- Árboles, bosques aleatorios y boosting
- Diagnóstico y mejora en problemas de aprendizaje supervisado
- Componentes principales y análisis de conglomerados

### Evaluación {-}

- Tareas semanales (20%)
- Examen parcial (30% práctico, 20% teórico)
- Un examen final (30% práctico)

### Material {-}

Cada semestre las notas cambian, en algunas partes considerablemente. Las
de este semestre están en [este repositorio](https://github.com/felipegonzalez/aprendizaje-maquina-mcd-2021),
incluyendo ejemplos, ejercicios y tareas.

### Referencias principales {-}

- [An Introduction to Statistical Learning](https://www.statlearning.com/), @ISL 
- [Deep Learning](https://www.deeplearningbook.org/), @Goodfellow-et-al-2016
- [Tidy Modeling with R](https://www.tmwr.org/)

### Otras referencias {-}

- [Pattern Recognition and Machine Learning](http://www.springer.com/us/book/9780387310732), @Bishop
- [The Elements of Statistical Learning](https://web.stanford.edu/~hastie/ElemStatLearn/), @ESL
- [Predicción conforme]()https://people.eecs.berkeley.edu/~angelopoulos/blog/posts/gentle-intro/

### Software: R y Rstudio {-}

Para hacer las tareas y exámenes pueden usar cualquier lenguaje o flujo de trabajo
que les convenga (R o Python, por ejemplo) - el único requisito esté basado en código y no
point-and-click. En lo posible utilizamos librerías especializadas
que se pueden utilizar desde varias plataformas (keras, por ejemplo).

- [R](https://cran.r-project.org) Sitio de R (CRAN)
- [Rstudio](https://www.rstudio.com/products/RStudio/) Interfaz gráfica para trabajar en R.
- [Recursos para aprender R](https://www.rstudio.com/online-learning/#R)

